2021-02-02 16:34:59,443 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:34:59,443 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:35:02,632 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:35:03,069 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:35:05,186 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:35:05,186 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:35:05,515 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:35:05,525 logger.py[line:50] INFO Had find the element //*[@id="details-button"] successful 
2021-02-02 16:35:05,552 logger.py[line:50] INFO The element xpath=>//*[@id="details-button"] was clicked.
2021-02-02 16:35:08,831 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:35:08,840 logger.py[line:50] INFO Had find the element //*[@id="proceed-link"] successful 
2021-02-02 16:35:39,757 logger.py[line:50] INFO The element xpath=>//*[@id="proceed-link"] was clicked.
2021-02-02 16:35:42,776 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:35:46,520 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:35:46,528 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:35:51,339 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:35:51,348 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/div/a[3] successful 
2021-02-02 16:35:51,546 logger.py[line:50] INFO The element xpath=>/html/body/div[1]/div/ul/li[3]/div/div/a[3] was clicked.
2021-02-02 16:35:54,561 logger.py[line:50] INFO Had find the element //*[@id="email"] successful 
2021-02-02 16:35:55,020 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:35:55,021 logger.py[line:50] INFO Had type ' 2770488802@qq.com
 ' in inputBox
2021-02-02 16:35:58,030 logger.py[line:50] INFO Had find the element //*[@id="password"] successful 
2021-02-02 16:36:02,920 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:36:02,921 logger.py[line:50] INFO Had type ' 123456
 ' in inputBox
2021-02-02 16:36:06,241 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:36:16,294 logger.py[line:53] ERROR NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="saveButton"]"}
  (Session info: chrome=88.0.4324.104)

2021-02-02 16:36:16,604 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:36:20,865 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEDF9F4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:22,867 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEDFABA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:24,870 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEDFAB908>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:29,019 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE4A43C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
2021-02-02 16:36:31,022 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE4A4E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
2021-02-02 16:36:33,024 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE4A4C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
2021-02-02 16:36:37,036 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE530E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:39,039 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE530FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:41,042 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE530B38>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72/screenshot
2021-02-02 16:36:45,190 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE64F390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
2021-02-02 16:36:47,192 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE64FE48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
2021-02-02 16:36:49,194 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014BEE64FC50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/5260f79cf153dd73033ce4f38614ab72
