2021-02-02 16:41:15,927 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:41:15,927 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:41:19,073 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:41:19,303 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:41:21,426 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:41:21,427 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:41:21,749 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:41:21,759 logger.py[line:50] INFO Had find the element //*[@id="details-button"] successful 
2021-02-02 16:41:21,786 logger.py[line:50] INFO The element xpath=>//*[@id="details-button"] was clicked.
2021-02-02 16:41:25,064 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:41:25,072 logger.py[line:50] INFO Had find the element //*[@id="proceed-link"] successful 
2021-02-02 16:41:37,266 logger.py[line:50] INFO The element xpath=>//*[@id="proceed-link"] was clicked.
2021-02-02 16:41:40,282 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:41:44,119 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:41:44,126 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:41:48,901 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:41:48,911 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/div/a[3] successful 
2021-02-02 16:41:49,113 logger.py[line:50] INFO The element xpath=>/html/body/div[1]/div/ul/li[3]/div/div/a[3] was clicked.
2021-02-02 16:41:56,341 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA979DC18>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:41:58,347 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA948AF28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:42:00,349 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA948AFD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:42:04,506 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9BC91D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
2021-02-02 16:42:06,512 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9BC9320>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
2021-02-02 16:42:08,514 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9BC9748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
2021-02-02 16:42:12,528 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9BC9128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:42:14,533 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9BC9C18>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:42:16,536 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9B45860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38/screenshot
2021-02-02 16:42:20,681 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9B54B00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
2021-02-02 16:42:22,683 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9B54C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
2021-02-02 16:42:24,686 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FA9B54E48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/39a260f3b2ec45796914d2cc3138dd38
