2021-02-02 16:44:15,567 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:44:15,567 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:44:18,795 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:44:19,018 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:44:21,132 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:44:21,133 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:44:21,449 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:21,458 logger.py[line:50] INFO Had find the element //*[@id="details-button"] successful 
2021-02-02 16:44:21,487 logger.py[line:50] INFO The element xpath=>//*[@id="details-button"] was clicked.
2021-02-02 16:44:24,765 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:24,773 logger.py[line:50] INFO Had find the element //*[@id="proceed-link"] successful 
2021-02-02 16:44:31,131 logger.py[line:50] INFO The element xpath=>//*[@id="proceed-link"] was clicked.
2021-02-02 16:44:34,143 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:44:37,990 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:37,997 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/span successful 
2021-02-02 16:44:42,796 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:42,806 logger.py[line:50] INFO Had find the element /html/body/div[1]/div/ul/li[3]/div/div/a[3] successful 
2021-02-02 16:44:43,478 logger.py[line:50] INFO The element xpath=>/html/body/div[1]/div/ul/li[3]/div/div/a[3] was clicked.
2021-02-02 16:44:46,486 logger.py[line:50] INFO Had find the element //*[@id="email"] successful 
2021-02-02 16:44:46,891 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:46,892 logger.py[line:50] INFO Had type ' 2770488802@qq.com ' in inputBox
2021-02-02 16:44:49,901 logger.py[line:50] INFO Had find the element //*[@id="password"] successful 
2021-02-02 16:44:50,284 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:50,285 logger.py[line:50] INFO Had type ' 123456 ' in inputBox
2021-02-02 16:44:53,616 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:53,633 logger.py[line:50] INFO Had find the element ' Login ' successful by id via value: saveButton 
2021-02-02 16:44:55,562 logger.py[line:50] INFO The element id=>saveButton was clicked.
2021-02-02 16:44:58,572 logger.py[line:50] INFO Had find the element //*[@id="querya"] successful 
2021-02-02 16:44:58,960 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:44:58,961 logger.py[line:50] INFO Had type ' flower earrings ' in inputBox
2021-02-02 16:45:16,085 logger.py[line:53] ERROR NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="J_Goods_List"]/div[1]/a/div[1]/img"}
  (Session info: chrome=88.0.4324.104)

2021-02-02 16:45:16,529 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-02-02 16:45:20,744 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE94D472E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:22,747 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE94A0FE48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:24,750 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE94A0F860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:28,916 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE959492B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
2021-02-02 16:45:30,918 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95949320>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
2021-02-02 16:45:32,920 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95949550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
2021-02-02 16:45:36,930 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95949208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:38,934 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95949D68>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:40,936 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95949F28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320/screenshot
2021-02-02 16:45:45,104 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95730400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
2021-02-02 16:45:47,108 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95730F60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
2021-02-02 16:45:49,111 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE95730C18>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/09333806d271925f7f6b3cc441c66320
