2021-02-01 14:52:16,197 logger.py[line:50] INFO You had select Chrome browser.
2021-02-01 14:52:16,197 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-01 14:52:16,847 remote_connection.py[line:388] DEBUG POST http://127.0.0.1:54369/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"extensions": [], "args": []}}}
2021-02-01 14:52:16,848 connectionpool.py[line:231] DEBUG Starting new HTTP connection (1): 127.0.0.1:54369
2021-02-01 14:52:19,841 connectionpool.py[line:461] DEBUG http://127.0.0.1:54369 "POST /session HTTP/1.1" 200 716
2021-02-01 14:52:19,842 remote_connection.py[line:440] DEBUG Finished Request
2021-02-01 14:52:19,842 logger.py[line:50] INFO Starting Chrome browser.
2021-02-01 14:52:19,843 remote_connection.py[line:388] DEBUG POST http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372/url {"url": "https://www.nhtest.com/"}
2021-02-01 14:52:20,206 connectionpool.py[line:461] DEBUG http://127.0.0.1:54369 "POST /session/dd06620d244a421079e9fca37cb63372/url HTTP/1.1" 200 14
2021-02-01 14:52:20,207 remote_connection.py[line:440] DEBUG Finished Request
2021-02-01 14:52:20,207 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-01 14:52:20,207 remote_connection.py[line:388] DEBUG POST http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372/window/maximize {}
2021-02-01 14:52:22,329 connectionpool.py[line:461] DEBUG http://127.0.0.1:54369 "POST /session/dd06620d244a421079e9fca37cb63372/window/maximize HTTP/1.1" 200 52
2021-02-01 14:52:22,329 remote_connection.py[line:440] DEBUG Finished Request
2021-02-01 14:52:22,330 logger.py[line:50] INFO Maximize the current window.
2021-02-01 14:52:22,330 remote_connection.py[line:388] DEBUG POST http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372/timeouts {"implicit": 10000}
2021-02-01 14:52:22,331 connectionpool.py[line:461] DEBUG http://127.0.0.1:54369 "POST /session/dd06620d244a421079e9fca37cb63372/timeouts HTTP/1.1" 200 14
2021-02-01 14:52:22,332 remote_connection.py[line:440] DEBUG Finished Request
2021-02-01 14:52:22,332 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-01 14:52:22,383 remote_connection.py[line:388] DEBUG DELETE http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372 {}
2021-02-01 14:52:22,424 connectionpool.py[line:461] DEBUG http://127.0.0.1:54369 "DELETE /session/dd06620d244a421079e9fca37cb63372 HTTP/1.1" 200 14
2021-02-01 14:52:22,425 remote_connection.py[line:440] DEBUG Finished Request
2021-02-01 14:52:24,502 remote_connection.py[line:388] DEBUG DELETE http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372 {}
2021-02-01 14:52:24,502 connectionpool.py[line:272] DEBUG Resetting dropped connection: 127.0.0.1
2021-02-01 14:52:26,679 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:26,680 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DADA668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:26,680 connectionpool.py[line:231] DEBUG Starting new HTTP connection (2): 127.0.0.1:54369
2021-02-01 14:52:28,685 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:28,686 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DA9AA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:28,686 connectionpool.py[line:231] DEBUG Starting new HTTP connection (3): 127.0.0.1:54369
2021-02-01 14:52:30,886 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:30,887 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DB69518>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:30,887 connectionpool.py[line:231] DEBUG Starting new HTTP connection (4): 127.0.0.1:54369
2021-02-01 14:52:33,245 remote_connection.py[line:388] DEBUG DELETE http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372 {}
2021-02-01 14:52:33,246 connectionpool.py[line:231] DEBUG Starting new HTTP connection (5): 127.0.0.1:54369
2021-02-01 14:52:35,255 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:35,255 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DB812B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:35,256 connectionpool.py[line:231] DEBUG Starting new HTTP connection (6): 127.0.0.1:54369
2021-02-01 14:52:37,260 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:37,261 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DB81710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:37,261 connectionpool.py[line:231] DEBUG Starting new HTTP connection (7): 127.0.0.1:54369
2021-02-01 14:52:39,264 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:39,264 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DB818D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:39,265 connectionpool.py[line:231] DEBUG Starting new HTTP connection (8): 127.0.0.1:54369
2021-02-01 14:52:41,284 remote_connection.py[line:388] DEBUG DELETE http://127.0.0.1:54369/session/dd06620d244a421079e9fca37cb63372 {}
2021-02-01 14:52:41,285 connectionpool.py[line:231] DEBUG Starting new HTTP connection (9): 127.0.0.1:54369
2021-02-01 14:52:43,291 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:43,291 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DADA5F8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:43,292 connectionpool.py[line:231] DEBUG Starting new HTTP connection (10): 127.0.0.1:54369
2021-02-01 14:52:45,530 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:45,530 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DADA6A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:45,531 connectionpool.py[line:231] DEBUG Starting new HTTP connection (11): 127.0.0.1:54369
2021-02-01 14:52:47,536 retry.py[line:575] DEBUG Incremented Retry for (url='/session/dd06620d244a421079e9fca37cb63372'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-02-01 14:52:47,536 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA3DADA9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/dd06620d244a421079e9fca37cb63372
2021-02-01 14:52:47,537 connectionpool.py[line:231] DEBUG Starting new HTTP connection (12): 127.0.0.1:54369
